server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: place
          uri: http://localhost:8082
          predicates:
            - Path=/accommodations/**, 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/paymentHistories/**, 
        - id: management
          uri: http://localhost:8084
          predicates:
            - Path=/reservationManagements/**, 
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=/logs/**, 
        - id: customer
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: place
          uri: http://place:8080
          predicates:
            - Path=/accommodations/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/paymentHistories/**, 
        - id: management
          uri: http://management:8080
          predicates:
            - Path=/reservationManagements/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/logs/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
