apiVersion: apps/v1
kind: Deployment
metadata:
  name: place
  labels:
    app: place
spec:
  replicas: 1
  selector:
    matchLabels:
      app: place
  template:
    metadata:
      labels:
        app: place
    spec:
      containers:
        - name: place
          image: chather/place:0224
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ORDER_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-dev
                  key: ORDER_LOG_LEVEL
          resources:
            requests:
              cpu: "200m"  
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5